# Generated by Django 3.1.1 on 2020-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_app', '0002_auto_20200926_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
