# Generated by Django 3.1.1 on 2020-09-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('see_app', '0005_topic_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='field_name',
        ),
    ]
