# Generated by Django 3.1.1 on 2020-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_app', '0006_remove_topic_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
