# Generated by Django 3.1.1 on 2020-10-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('see_app', '0007_topic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
    ]
