# Generated by Django 3.1.1 on 2020-10-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_app', '0011_auto_20201020_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_added'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Созданно'),
        ),
    ]
